networks:
  apitemplate-backend:
    name: apitemplate-backend
  backend:
    name: backend
    external: true

services:
  apitemplate.redis:
    container_name: apitemplate.redis
    image: redis:latest
    restart: always
    ports:
      - 8003:6379
    networks:
      - apitemplate-backend
  apitemplate.db:
    container_name: apitemplate.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    image: postgres:latest
    restart: always
    volumes:
      - appdata:/var/lib/postgresql/data
    ports:
      - 8002:5432
    networks:
      - apitemplate-backend
  apitemplate.seq:
    container_name: apitemplate.seq
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8004:80
    networks:
      - apitemplate-backend
    volumes:
      - logdata:/data
  apitemplate.api.green:
    container_name: apitemplate.api.green
    image: apitemplate.api
    build:
      context: .
      dockerfile: src/ApiTemplate.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=apitemplate.db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
      - ConnectionStrings__Redis=apitemplate.redis:6379
      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
      - JwtSettings__ExpiryMinutes=10
      - JwtSettings__Issuer=ApiTemplate
      - JwtSettings__Audience=ApiTemplate  
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1__Name=WithProperty
      - Serilog__Enrich__1__Args__name=MachineName
      - Serilog__Enrich__1__Args__value=${HOSTNAME}
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=File
      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
      - Serilog__WriteTo__1__Args__path=/var/log/api/log-.txt
      - Serilog__WriteTo__1__Args__rollingInterval=Day
      - Serilog__WriteTo__2__Name=Seq
      - Serilog__WriteTo__2__Args__serverUrl=http://apitemplate.seq:5341
      - Serilog__Enrich__2__Name=WithProperty
      - Serilog__Enrich__2__Args__name=Application
      - Serilog__Enrich__2__Args__value=ApiTemplate
    ports:
      - 8100:80
    networks:
      - apitemplate-backend
      - backend
    volumes:
      - logdata:/var/logs
#  apitemplate.api.blue:
#    container_name: apitemplate.api.blue
#    image: apitemplate.api
#    build:
#      context: .
#      dockerfile: src/apitemplate.Api/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://*:80
#      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=apitemplate.db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
#      - ConnectionStrings__Redis=apitemplate.redis:6379
#      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
#      - JwtSettings__ExpiryMinutes=10
#      - JwtSettings__Issuer=ApiTemplate
#      - JwtSettings__Audience=ApiTemplate
#    ports:
##      - "${ADDRESS}:8200:80"
#      - 8200:80
#    depends_on:
#      - apitemplate.db
#      - apitemplate.redis
#      - apitemplate.seq
#    networks:
#      - apitemplate-backend
#  apitemplate.api.white:
#    container_name: apitemplate.api.white
#    image: apitemplate.api
#    build:
#      context: .
#      dockerfile: src/apitemplate.Api/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://*:80
#      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=apitemplate.db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
#      - ConnectionStrings__Redis=apitemplate.redis:6379
#      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
#      - JwtSettings__ExpiryMinutes=10
#      - JwtSettings__Issuer=ApiTemplate
#      - JwtSettings__Audience=ApiTemplate
#    ports:
##      - "${ADDRESS}:8300:80"
##      - "${ADDRESS}:8301:443"
#      - 8300:80
#      - 8301:443
#    depends_on:
#      - apitemplate.db
#      - apitemplate.redis
#      - apitemplate.seq
#    networks:
#      - apitemplate-backend
#  apitemplate.loadbalancer:
#    container_name: apitemplate.loadbalancer
#    image: apitemplate.loadbalancer
#    build:
#      context: .
#      dockerfile: src/apitemplate.LoadBalancer/Dockerfile
#    restart: always
#    ports:
##      - "${ADDRESS}:8001:80"
#      - 8001:80
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://*:80
#      - ReverseProxy__Clusters__api__Destinations__green__Address=http://apitemplate.api.green:80
#      - ReverseProxy__Clusters__api__Destinations__blue__Address=http://apitemplate.api.blue:80
#      - ReverseProxy__Clusters__api__Destinations__white__Address=http://apitemplate.api.white:80
#      - ReverseProxy__Clusters__api__LoadBalancingPolicy=RoundRobin
#      - ReverseProxy__Routes__api__ClusterId=api
#      - ReverseProxy__Routes__api__Match__Path={**catch-all}
#      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=apitemplate.db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
#      - ConnectionStrings__Redis=apitemplate.redis:6379
#      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
#      - JwtSettings__ExpiryMinutes=10
#      - JwtSettings__Issuer=ApiTemplate
#      - JwtSettings__Audience=ApiTemplate
#    depends_on:
#      - apitemplate.api.green
#      - apitemplate.api.blue
#      - apitemplate.api.white
#    networks:
#      - apitemplate-backend

volumes:
  appdata:
  logdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:/Log/ApiTemplate'