networks:
  apitemplate-backend:
    name: apitemplate-backend
  backend:
    name: backend
    external: true

services:
  apitemplate.api.green:
    container_name: apitemplate.api.green
    image: apitemplate.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=applepi-db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
      - ConnectionStrings__Redis=redis-stack:6379
      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
      - JwtSettings__ExpiryMinutes=10
      - JwtSettings__Issuer=ApiTemplate
      - JwtSettings__Audience=ApiTemplate  
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1__Name=WithProperty
      - Serilog__Enrich__1__Args__name=MachineName
      - Serilog__Enrich__1__Args__value=${HOSTNAME}
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=File
      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
      - Serilog__WriteTo__1__Args__path=/var/logs/log.txt
      - Serilog__WriteTo__1__Args__rollingInterval=Day
      - Serilog__WriteTo__2__Name=Seq
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
      - Serilog__Enrich__2__Name=WithProperty
      - Serilog__Enrich__2__Args__name=Application
      - Serilog__Enrich__2__Args__value=ApiTemplate
    ports:
      - 8100:80
    networks:
      - apitemplate-backend
      - backend
    volumes:
      - logdata:/var/logs
#  apitemplate.api.blue:
#    container_name: apitemplate.api.blue
#    image: apitemplate.api
#    build:
#      context: .
#      dockerfile: src/ApiTemplate.Api/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://*:80
#      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=applepi-db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
#      - ConnectionStrings__Redis=redis-stack:6379
#      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
#      - JwtSettings__ExpiryMinutes=10
#      - JwtSettings__Issuer=ApiTemplate
#      - JwtSettings__Audience=ApiTemplate  - Serilog__MinimumLevel__Override__Microsoft=Warning
#      - Serilog__MinimumLevel__Override__System=Warning
#      - Serilog__Enrich__0=FromLogContext
#      - Serilog__Enrich__1__Name=WithProperty
#      - Serilog__Enrich__1__Args__name=MachineName
#      - Serilog__Enrich__1__Args__value=${HOSTNAME}
#      - Serilog__WriteTo__0__Name=Console
#      - Serilog__WriteTo__1__Name=File
#      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
#      - Serilog__WriteTo__1__Args__path=/var/logs/log.txt
#      - Serilog__WriteTo__1__Args__rollingInterval=Day
#      - Serilog__WriteTo__2__Name=Seq
#      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
#      - Serilog__Enrich__2__Name=WithProperty
#      - Serilog__Enrich__2__Args__name=Application
#      - Serilog__Enrich__2__Args__value=ApiTemplate
#    ports:
#      - 8100:80
#    networks:
#      - apitemplate-backend
#      - backend
#    volumes:
#      - logdata:/var/logs
#  apitemplate.api.white:
#    container_name: apitemplate.api.white
#    image: apitemplate.api
#    build:
#      context: .
#      dockerfile: src/ApiTemplate.Api/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://*:80
#      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=applepi-db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
#      - ConnectionStrings__Redis=redis-stack:6379
#      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
#      - JwtSettings__ExpiryMinutes=10
#      - JwtSettings__Issuer=ApiTemplate
#      - JwtSettings__Audience=ApiTemplate  - Serilog__MinimumLevel__Override__Microsoft=Warning
#      - Serilog__MinimumLevel__Override__System=Warning
#      - Serilog__Enrich__0=FromLogContext
#      - Serilog__Enrich__1__Name=WithProperty
#      - Serilog__Enrich__1__Args__name=MachineName
#      - Serilog__Enrich__1__Args__value=${HOSTNAME}
#      - Serilog__WriteTo__0__Name=Console
#      - Serilog__WriteTo__1__Name=File
#      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
#      - Serilog__WriteTo__1__Args__path=/var/logs/log.txt
#      - Serilog__WriteTo__1__Args__rollingInterval=Day
#      - Serilog__WriteTo__2__Name=Seq
#      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
#      - Serilog__Enrich__2__Name=WithProperty
#      - Serilog__Enrich__2__Args__name=Application
#      - Serilog__Enrich__2__Args__value=ApiTemplate
#    ports:
#      - 8100:80
#    networks:
#      - apitemplate-backend
#      - backend
#    volumes:
#      - logdata:/var/logs
  apitemplate.loadbalancer:
    container_name: apitemplate.loadbalancer
    image: apitemplate.loadbalancer
    restart: always
    ports:
#      - "${ADDRESS}:8001:80"
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - ReverseProxy__Clusters__api__Destinations__green__Address=http://apitemplate.api.green:80
#      - ReverseProxy__Clusters__api__Destinations__blue__Address=http://apitemplate.api.blue:80
#      - ReverseProxy__Clusters__api__Destinations__white__Address=http://apitemplate.api.white:80
      - ReverseProxy__Clusters__api__LoadBalancingPolicy=RoundRobin
      - ReverseProxy__Routes__api__ClusterId=api
      - ReverseProxy__Routes__api__Match__Path={**catch-all}
      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=applepi-db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
      - ConnectionStrings__Redis=redis-stack:6379
      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
      - JwtSettings__ExpiryMinutes=10
      - JwtSettings__Issuer=ApiTemplate
      - JwtSettings__Audience=ApiTemplate
    depends_on:
      - apitemplate.api.green
#      - apitemplate.api.blue
#      - apitemplate.api.white
    networks:
      - apitemplate-backend

volumes:
  appdata:
  logdata:
    driver: local